// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load @"load-references.fsx"
#load @"..\Common.fs"
      @"..\DayOne.fs"
      @"..\DayTwo.fs"
      @"..\DayThree.fs"
      @"..\DayFour.fs"
      @"..\DayFive.fs"
      @"..\DaySix.fs"
      @"..\DaySeven.fs"
      @"..\DayEight.fs"
      @"..\DayNine.fs"
      @"..\DayTen.fs"
      @"..\DayEleven.fs"
      @"..\DayTwelve.fs"
      @"..\DayThirteen.fs"
      @"..\DayFourteeen.fs"
      @"..\DayFifteen.fs"
      @"..\DaySixteen.fs"
      @"..\DaySeventeen.fs"
      @"..\DayEighteen.fs"
      @"..\DayNineteen.fs"
      @"..\DayTwenty.fs"
      @"..\DayTwentyOne.fs"
      @"..\DayTwentyTwo.fs"
      @"..\DayTwentyThree.fs"
      @"..\DayTwentyFour.fs"
      @"..\DayTwentyFive.fs"
      @"..\Nonogram.fs"
